### PR TITLE
Rename SUMMARY.md to README.md

### PR DESCRIPTION
**Pull request by cjoshmartin**
I changed this so people don't have to click SUMMARY.md to reference links in this book.

### CODE REVIEW

**Comment by hayeah** [comment]
let me do this separately. SUMMARY.md is a gitbook specific file

**Comment by hayeah** [comment]
oh crap, there are other commits, reopened

**Comment by hayeah** [comment]
The command to start docker uses the flag:

```
-v `pwd`:/dapp 
```

This is command substitution. Which shell are you using? I checked zsh, sh, bash, and all they accept the backtick syntax...

**Comment by cjoshmartin** [comment]
I use fish shell

**Pull request closed without merging**
